# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Forder',
            fields=[
                ('user', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbai', models.CharField(max_length=250)),
                ('ma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musicid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('tenbai', models.CharField(max_length=250)),
                ('ma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('user', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
