# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbai', models.CharField(max_length=250)),
                ('ma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musicid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbai', models.CharField(max_length=250)),
                ('ma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('user', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Forder',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lsb.Username')),
                ('ma', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='musicid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsb.Username'),
        ),
    ]
