# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 04:37
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0002_credentialsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='credential',
        ),
        migrations.AddField(
            model_name='credentialsmodel',
            name='cred',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
