# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0003_auto_20180517_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
