# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0004_auto_20180517_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forder',
            name='user',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
