# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0005_auto_20180517_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicid',
            name='id',
        ),
        migrations.AlterField(
            model_name='musicid',
            name='user',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
